# Generated by Django 4.2.7 on 2025-08-22 22:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'ordering': ['-date_of_accident'], 'verbose_name': 'Accident Report', 'verbose_name_plural': 'Accident Reports'},
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='incident_type',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='injured_person',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='ambulance_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='ambulance_caller',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='ambulance_time_arrived',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='ambulance_time_called',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='consent_to_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='continued_activities_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='date_of_accident',
            field=models.DateField(default=datetime.datetime(2025, 8, 22, 22, 46, 21, 975709, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='first_aider_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='first_aider_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='first_aider_signature',
            field=models.ImageField(blank=True, help_text='Digital signature of the first aider', null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='first_aider_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='hospital',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='how_occurred',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='injury_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='injury_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='phone_home',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='refusal_of_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='riddor_date_reported',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='riddor_report_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='riddor_reportable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='riddor_reported_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='surname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='time_departure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='time_of_accident',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='treatment_given',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='StaffAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appraisal', models.DateField()),
                ('attendance_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('attendance_comments', models.TextField(blank=True)),
                ('quality_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('quality_comments', models.TextField(blank=True)),
                ('teamwork_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('teamwork_comments', models.TextField(blank=True)),
                ('initiative_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('initiative_comments', models.TextField(blank=True)),
                ('customer_service_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('customer_service_comments', models.TextField(blank=True)),
                ('adherence_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('adherence_comments', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('development_needs', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appraiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_appraisals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Appraisal',
                'verbose_name_plural': 'Staff Appraisals',
                'ordering': ['-date_of_appraisal'],
            },
        ),
    ]
