# Generated by Django 4.2.7 on 2025-08-29 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_cafechecklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafechecklist',
            options={'ordering': ['checklist_type', 'item_id']},
        ),
        migrations.AddField(
            model_name='cafechecklist',
            name='checklist_type',
            field=models.CharField(blank=True, choices=[('opening', 'Opening Checklist'), ('midday', 'Midday Operations'), ('closing', 'Closing Checklist')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafechecklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafechecklist',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_creators', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafechecklist',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cafechecklist',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='cafechecklist',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cafechecklist',
            unique_together={('date', 'checklist_type', 'item_id')},
        ),
    ]
