# Generated by Django 4.2.7 on 2025-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_cafechecklist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('overall_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('cleanliness_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('staff_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('facilities_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('value_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comments', models.TextField(blank=True)),
                ('would_recommend', models.BooleanField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='dailystats',
            name='bounce_time_minutes',
            field=models.IntegerField(default=0, help_text='Total bounce time in minutes'),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='peak_hour_end',
            field=models.TimeField(blank=True, help_text='Peak hour end time', null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='peak_hour_start',
            field=models.TimeField(blank=True, help_text='Peak hour start time', null=True),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total daily revenue', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('revenue', 'Monthly Revenue'), ('visitors', 'Monthly Visitors'), ('satisfaction', 'Customer Satisfaction'), ('incidents', 'Safety Incidents')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('target_type', 'month', 'year')},
            },
        ),
    ]
