# Generated by Django 4.2.7 on 2025-09-04 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_customersatisfactionsurvey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('wc_number', models.CharField(blank=True, help_text='WC number from the form', max_length=50)),
                ('inspection_day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], help_text='Day of the week', max_length=3)),
                ('inspector_initials', models.CharField(help_text='Inspector initials', max_length=5)),
                ('manager_initials', models.CharField(help_text='Manager initials for sign-off', max_length=5)),
                ('framework_stability', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS001: Framework Stability & Security', max_length=8)),
                ('perimeter_netting', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS002: Perimeter Netting', max_length=8)),
                ('wall_padding', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS003: Protective Wall Padding', max_length=8)),
                ('walkway_padding', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS004: Protective Walkway Padding', max_length=8)),
                ('coverall_pads', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS005: Coverall Pads', max_length=8)),
                ('trampoline_beds', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS006: Trampoline Beds', max_length=8)),
                ('safety_netting', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS007: Trampoline Safety Netting', max_length=8)),
                ('trampoline_springs', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS008: Trampoline Springs', max_length=8)),
                ('fire_doors', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS009: Fire Doors Functioning & Routes Clear', max_length=8)),
                ('fire_equipment', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS010: Fire Extinguishing Equipment In Place', max_length=8)),
                ('electrical_cables', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS011: Electrical Cables Safely Routed', max_length=8)),
                ('electrical_sockets', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS012: Electrical plugs and sockets in good condition', max_length=8)),
                ('first_aid_box', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS013: First-aid box fully stocked', max_length=8)),
                ('signage', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS014: Signage in place and visible', max_length=8)),
                ('area_cleanliness', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS015: Area clean and ready for use', max_length=8)),
                ('gates_locks', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS016: Gates, closing and locking devices operational', max_length=8)),
                ('trip_hazards', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS017: Area free of trip/slip hazards', max_length=8)),
                ('staff_availability', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('remedial', 'Remedial')], default='pass', help_text='INS018: Minimum required staff available', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_inspections', to=settings.AUTH_USER_MODEL)),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signed_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Inspection',
                'verbose_name_plural': 'Daily Inspections',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('date', 'inspection_day')},
            },
        ),
        migrations.CreateModel(
            name='RemedialAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_code', models.CharField(help_text='Inspection code (e.g., INS001)', max_length=6)),
                ('issue_description', models.TextField(help_text='Description of the issue found')),
                ('remedial_action', models.TextField(help_text='Action taken or required')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('escalated', 'Escalated')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_remedial_actions', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_remedial_actions', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedial_actions', to='forms.dailyinspection')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_remedial_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remedial Action',
                'verbose_name_plural': 'Remedial Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
