# Generated by Django 4.2.7 on 2025-09-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_dailyinspection_remedialaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyinspection',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dailyinspection',
            name='inspection_day',
        ),
    ]
