# Generated by Django 4.2.7 on 2025-09-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_dailyinspection_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('signature', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='waivers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
