# Generated by Django 4.2.7 on 2025-09-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_waiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiver',
            name='signed_by',
        ),
    ]
