# Generated by Django 4.2.7 on 2025-09-29 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_remove_waiver_signed_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waiver',
            options={'ordering': ['-signed_at']},
        ),
        migrations.RenameField(
            model_name='waiver',
            old_name='created_at',
            new_name='signed_at',
        ),
        migrations.AddField(
            model_name='waiver',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waiver',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='waivers/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='WaiverSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('participant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiver_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='waiver',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiver', to='forms.waiversession'),
        ),
    ]
