# Generated by Django 4.2.7 on 2025-10-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_alter_waiver_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('marshal', 'Marshal'), ('reception', 'Reception'), ('party_host', 'Party Host'), ('cafe', 'Cafe')], default='staff', max_length=10),
        ),
    ]
