# Generated by Django 4.2.7 on 2025-10-12 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarshalChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('checklist_type', models.CharField(blank=True, choices=[('pre_shift', 'Pre-Shift Marshal Checklist'), ('shift_operations', 'Shift Operations Checklist'), ('post_shift', 'Post-Shift Marshal Checklist'), ('emergency', 'Emergency Response Checklist')], max_length=50, null=True)),
                ('item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marshal_checklist_creators', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marshal_checklist_updaters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marshal Checklist',
                'verbose_name_plural': 'Marshal Checklists',
                'ordering': ['checklist_type', 'item_id'],
                'unique_together': {('date', 'checklist_type', 'item_id')},
            },
        ),
    ]
