# Generated by Django 4.2.7 on 2025-10-13 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_marshalchecklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marshalchecklist',
            options={'ordering': ['checklist_type', 'item_id']},
        ),
        migrations.AlterField(
            model_name='marshalchecklist',
            name='checklist_type',
            field=models.CharField(blank=True, choices=[('pre_shift', 'Pre-Shift Marshal Checklist'), ('shift_operations', 'Shift Operations Checklist'), ('post_shift', 'Post-Shift Marshal Checklist')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marshalchecklist',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marshal_checklist_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
